apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
        
    spec:
      containers:
        - name: helloworld
          image: 'gcr.io/virtual-anchor-319409/helloworld:latest'
          imagePullPolicy: Always
          terminationMessagePath: /var/log/termination
          resources:
            requests:
              memory: 250Mi
              cpu: 500m
            limits:
              memory: 500Mi
              cpu: 1000m
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 60
            exec:
              command:
                - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            successThreshold: 2
            exec:
              command:
                - cat /tmp/healthy
